version: "3.3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 3333:443
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/certs:ro

